export const metadata={title:"Pricing",description:"Approved DripFunnel pricing for websites, e-commerce and Technology-Driven Marketing services."};
import Link from "next/link";
const plans=[
["WEBSITE","Static Website","₹6,999","+ GST",["7–8 pages","Responsive design","WhatsApp integration","Google Maps","Lead capture form","Professional business design","3 revisions","One-time development"],"₹1,999/year maintenance"],
["WEBSITE","Blog Website","₹9,999","+ GST",["Blog/content capability"],"Maintenance not specified in the supplied business specification"],
["E-COMMERCE","Basic","₹9,999","+ GST",["Up to 100 products","Product management","Payment gateway","Shipping integration","Cart","Checkout","Order management","Admin portal","Responsive design"],"₹2,999/year maintenance"],
["E-COMMERCE","Standard","₹12,999","+ GST",["Up to 250 products","5 users","Inventory management","Custom/advanced design","Dedicated manager"],"₹3,999/year maintenance"],
["E-COMMERCE","Enterprise","₹29,999","+ GST",["Up to 10 users","Advanced customization","Advanced business-specific functionality"],"₹7,999/year maintenance"],
["MARKETING","Meta Ads","₹2,500","/month",["Campaign management"],"Advertising platform spend is separate"],
["MARKETING","Google Ads","₹3,500","/month",["Campaign management"],"Advertising platform spend is separate"],
["MARKETING","Social Media Creatives","₹1,999","/month",["Creative content support"],"Advertising platform spend is separate"],
["MARKETING","Ads Setup","₹2,999","one-time",["Ads setup"],"Advertising platform spend is separate"]];
export default function Pricing(){return <><section className="page-hero"><div className="container"><div className="eyebrow">PRICING</div><h1>Clear pricing. <em>No unnecessary complexity.</em></h1><p>Approved DripFunnel pricing for websites, e-commerce and Technology-Driven Marketing services.</p></div></section><section className="section"><div className="container pricing-full">{plans.map((p,i)=><div className={`price-row ${i===2?"accent-row":""}`} key={`${p[0]}-${p[1]}`}><div><small>{p[0]}</small><h2>{p[1]}</h2></div><div className="price-big">{p[2]} <small>{p[3]}</small></div><ul className="feature-list">{p[4].map(x=><li key={x}>{x}</li>)}</ul><strong>{p[5]}</strong><Link href="/contact">Get a Quote ↗</Link></div>)}<p className="price-note">Advertising platform spend is separate from DripFunnel management/setup fees. All listed website prices are + GST.</p></div></section><section className="section ownership"><div className="container ownership-inner"><h2>Build Once. <em>Own Your Website.</em></h2><p>Website and e-commerce development are provided as a one-time development service rather than forcing customers into a monthly website subscription. Annual maintenance is based on the selected plan. Additional pages, major changes, new functionality and custom integrations may incur additional charges.</p><Link className="btn btn-dark" href="/contact">Get a Quote</Link></div></section></>;}
